### ISSUE TITLE
Org name case sensitivity

### ISSUE THREAD

**Issue by toddoconnor** [casa-vega/issue-ops#178]
If the entitlements file has Org in upper case, and user passes in lower case, it fails.
If the entitlements file has Org in upper case, and user passes in upper case, it fails (since we lc the input).

```
{"organization_error": "invalid organization: orgname-emu"}
```

**Comment by cvega** [comment]
We can lower case org names, but org names in entitlements should always be lowercase, we're doing a string match and we probably don't want to get too fancy here.

**Comment by cvega** [comment]
fixed

**Comment by cvega** [comment]
32
