### ISSUE TITLE
Update ISSUE_TEMPLATE/repo-toggle-visibility.yml

### ISSUE THREAD

**Issue by toddoconnor** [casa-vega/issue-ops#182]
This template is looking for the helper action of the old name `repo-update-visibility`. Change two occurrences in the file to `repo-toggle-visibility`.

<img width="650" alt="Screenshot 2023-06-07 at 1 09 20 PM" src="https://github.com/casa-vega/issue-ops/assets/103966065/9217975b-d722-4427-98fe-75545ca717e8">

**Comment by cvega** [comment]
@toddoconnor fixed:

https://github.com/casa-vega/issue-ops/issues/211

![image](https://github.com/casa-vega/issue-ops/assets/376532/13e9bd00-9107-44ef-945d-24ea28554b84)
