### ISSUE TITLE
list admins cannot be run when user is not in entitlement

### ISSUE THREAD

**Issue by toddoconnor** [casa-vega/issue-ops#183]
`list admins` can be run by anyone and this is esp. useful for non-admins. Users do not need to be listed in the entitlement. 

I see this error when I try to get the admins for any Org. I am not listed as an admin for the Org but I should still be able to find out who my admins are. 

```
{"auth_error": "user does not have permissions: USERIDHERE"}
```

**Comment by cvega** [comment]
@toddoconnor fixed: https://github.com/casa-vega/issue-ops/issues/193, returns two admins that aren't me
