### ISSUE TITLE
Creating a repo webhook fails with no message

### ISSUE THREAD

**Issue by toddoconnor** [casa-vega/issue-ops#184]
Creating a repo webhook fails with no message. Looking at the Actions I see this:

<img width="1118" alt="Screenshot 2023-06-07 at 4 01 41 PM" src="https://github.com/casa-vega/issue-ops/assets/103966065/2ee655a1-b499-441b-820b-22aa79203363">

**Comment by cvega** [comment]
@toddoconnor fixed:

https://github.com/casa-vega/issue-ops/issues/196

![image](https://github.com/casa-vega/issue-ops/assets/376532/e15823bf-ea86-4c44-a829-1ebac8783049)

![image](https://github.com/casa-vega/issue-ops/assets/376532/2e863cfd-e5a7-4cb5-94f5-adcb446f3eef)
