### ISSUE TITLE
Cannot set org level variable

### ISSUE THREAD

**Issue by toddoconnor** [casa-vega/issue-ops#186]
Using lower case Org name as param and in entitlement, I see this message in the Issue.

```
{"organization_error": "invalid organization: "}
```

**Comment by cvega** [comment]
@toddoconnor fixed

https://github.com/casa-vega/issue-ops/issues/204

![image](https://github.com/casa-vega/issue-ops/assets/376532/848481cb-a754-470c-9f30-5522bcede869)

![image](https://github.com/casa-vega/issue-ops/assets/376532/b9b196bf-3f5c-4560-809b-278b4dca6dd8)

Also includes specifying individual repos:

![image](https://github.com/casa-vega/issue-ops/assets/376532/4b3d850a-d652-4aea-98f4-a433c3e87f43)
